### ISSUE TITLE
Update to GNOME 40 (or 3.38)

### ISSUE THREAD

**Issue by Eonfge** [flathub/net.mancubus.SLADE#25]
Currently there is an upstream issue with GCC 10.2 which prevents us from compiling on FreeDesktop 20.08 and derivatives:
https://github.com/sirjuddington/SLADE/issues/1209

Once upstream has finalized a new release, we can update the package. At the time of writing, there is a 3.2beta but it's unclear when that finalizes.

**Comment by Calinou** [comment]
Fixed by https://github.com/flathub/net.mancubus.SLADE/pull/27.
