### ISSUE TITLE
Doesn't start on Wayland

### ISSUE THREAD

**Issue by JoshuaFern** [flathub/net.mancubus.SLADE#43]
`Error: Unable to initialize GTK+, is DISPLAY set properly?`

Workaround was to enable socket=wayland with Flatseal

**Comment by Eonfge** [comment]
This does sound like a user-error, I can;t reproduce it on Wayland.

Can you tell me what version of Flatpak you use and what your display setup is?

**Comment by JoshuaFern** [comment]
Running Flatpak 1.12.7 on Hyprland

**Comment by Eonfge** [comment]
Do you have any recommended distribution to use Hyprland with? Also, what version of XWayland do you have? It's needed if you want to run X11 applications

**Comment by JoshuaFern** [comment]
I'm using hyprland on NixOS using the flake to use the latest master. You can try it on Arch as well via the AUR.

Running Xwayland 22.1.3

Not sure what's wrong here. I use a lot of flatpak apps every day and they work great, many on Xwayland. however last night I tested a bunch of new Flatpak apps and found a couple that seem to throw the same error so I don't think it's entirely SLADE specific. For example, io.github.Soundux and com.github.gabutakut.gabutdm

**Comment by JoshuaFern** [comment]
Closing this as it's stale and I'm using X11 again.
